language: python
python:
  - "3.6"
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install -r requirements.txt
services:
 - postgresql

before_script:
#  - psql -c "CREATE DATABASE testingdb;"

script:
  - export MAIN_DATABASE_URL="dbname='postgres' host='127.0.0.1' port='5432' user='postgres' password='12345'"
  
  - export TEST_DATABASE_URL = "dbname='testingdb' host='127.0.0.1' port='5432' user='postgres' password='12345'"
  - pytest --cov=app
after_success:
  - coveralls


  